package com.urosjarc.mapmaster.domain
class OsmMap(
	val minLat: Double,
	val minLon: Double,
	val maxLat: Double,
	val maxLon: Double
) {

	val aerialway = mutableListOf<Aerialway>()
	val aeroway = mutableListOf<Aeroway>()
	val amenity = mutableListOf<Amenity>()
	val barrier = mutableListOf<Barrier>()
	val boundary = mutableListOf<Boundary>()
	val building = mutableListOf<Building>()
	val entrance = mutableListOf<Entrance>()
	val craft = mutableListOf<Craft>()
	val emergency = mutableListOf<Emergency>()
	val lifeguard = mutableListOf<Lifeguard>()
	val geological = mutableListOf<Geological>()
	val highway = mutableListOf<Highway>()
	val footway = mutableListOf<Footway>()
	val cycleway = mutableListOf<Cycleway>()
	val busway = mutableListOf<Busway>()
	val junction = mutableListOf<Junction>()
	val service = mutableListOf<Service>()
	val historic = mutableListOf<Historic>()
	val landuse = mutableListOf<Landuse>()
	val leisure = mutableListOf<Leisure>()
	val man_made = mutableListOf<Man_made>()
	val military = mutableListOf<Military>()
	val natural = mutableListOf<Natural>()
	val office = mutableListOf<Office>()
	val place = mutableListOf<Place>()
	val power = mutableListOf<Power>()
	val line = mutableListOf<Line>()
	val public_transport = mutableListOf<Public_transport>()
	val railway = mutableListOf<Railway>()
	val route = mutableListOf<Route>()
	val shop = mutableListOf<Shop>()
	val sport = mutableListOf<Sport>()
	val telecom = mutableListOf<Telecom>()
	val tourism = mutableListOf<Tourism>()
	val water = mutableListOf<Water>()
	val waterway = mutableListOf<Waterway>()
	val hazard = mutableListOf<Hazard>()
	val access = mutableListOf<Access>()
	val maxaxleload = mutableListOf<Maxaxleload>()
	val maxheight = mutableListOf<Maxheight>()
	val maxlength = mutableListOf<Maxlength>()
	val maxspeed = mutableListOf<Maxspeed>()
	val maxweight = mutableListOf<Maxweight>()
	val maxwidth = mutableListOf<Maxwidth>()
	val minspeed = mutableListOf<Minspeed>()
	val traffic_sign = mutableListOf<Traffic_sign>()

	fun addMapFeature(feature: OsmFeature){
		when(feature){
			is Aerialway -> this.aerialway.add(feature)
			is Aeroway -> this.aeroway.add(feature)
			is Amenity -> this.amenity.add(feature)
			is Barrier -> this.barrier.add(feature)
			is Boundary -> this.boundary.add(feature)
			is Building -> this.building.add(feature)
			is Entrance -> this.entrance.add(feature)
			is Craft -> this.craft.add(feature)
			is Emergency -> this.emergency.add(feature)
			is Lifeguard -> this.lifeguard.add(feature)
			is Geological -> this.geological.add(feature)
			is Highway -> this.highway.add(feature)
			is Footway -> this.footway.add(feature)
			is Cycleway -> this.cycleway.add(feature)
			is Busway -> this.busway.add(feature)
			is Junction -> this.junction.add(feature)
			is Service -> this.service.add(feature)
			is Historic -> this.historic.add(feature)
			is Landuse -> this.landuse.add(feature)
			is Leisure -> this.leisure.add(feature)
			is Man_made -> this.man_made.add(feature)
			is Military -> this.military.add(feature)
			is Natural -> this.natural.add(feature)
			is Office -> this.office.add(feature)
			is Place -> this.place.add(feature)
			is Power -> this.power.add(feature)
			is Line -> this.line.add(feature)
			is Public_transport -> this.public_transport.add(feature)
			is Railway -> this.railway.add(feature)
			is Route -> this.route.add(feature)
			is Shop -> this.shop.add(feature)
			is Sport -> this.sport.add(feature)
			is Telecom -> this.telecom.add(feature)
			is Tourism -> this.tourism.add(feature)
			is Water -> this.water.add(feature)
			is Waterway -> this.waterway.add(feature)
			is Hazard -> this.hazard.add(feature)
			is Access -> this.access.add(feature)
			is Maxaxleload -> this.maxaxleload.add(feature)
			is Maxheight -> this.maxheight.add(feature)
			is Maxlength -> this.maxlength.add(feature)
			is Maxspeed -> this.maxspeed.add(feature)
			is Maxweight -> this.maxweight.add(feature)
			is Maxwidth -> this.maxwidth.add(feature)
			is Minspeed -> this.minspeed.add(feature)
			is Traffic_sign -> this.traffic_sign.add(feature)
		}
	}
}